apiVersion: apps/v1
kind: Deployment
metadata:
  name: shahboz-devsecops-project-2-cd
  labels:
    app: shahboz-devsecops-project-2-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shahboz-devsecops-project-2-cd
  template:
    metadata:
      labels:
        app: shahboz-devsecops-project-2-cd
    spec:
      containers:
      - name: shahboz-devsecops-project-2-cd
        image: shahboz01/democicd:2
        ports:
        - containerPort: 8080
