apiVersion: v1
kind: Service
metadata:
  name: shahboz-devsecops-project-2-cd
  labels:
    app: shahboz-devsecops-project-2-cd
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    app: shahboz-devsecops-project-2-cd
